version: "3.8"

services:
  frontend:
    container_name: vite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Map port 80 (Nginx) to 5173 (local)
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    container_name: nestjs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 (NestJS) to 3000 (local)
    volumes:
      - /app/node_modules
      - ./backend:/app
    command: npm run start:dev
    environment:
      - NODE_ENV=development
